name: blue-caller

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    if:  ${{ inputs.username }} == 'Blue'

    steps:
      - name: Hello User
        run: echo Hello, ${{ inputs.username }}

