name: called

on:

  workflow_dispatch:
    inputs:
      username:
        required: true
        type: choice
        options:
        - Blue
        - Green


jobs:
  call-workflow-A:
    if: github.event.inputs.username == 'Blue'
    uses: bakuppus/github-action-reuseable-workflow-multiple-inputs/.github/workflows/blue-workflow-caller.yaml@dev
    with:
      username:  ${{ inputs.username }}
    secrets:
      token: ${{ secrets.CICD_GIT_TOKEN }}

  call-workflow-B:
    if: github.event.inputs.username == 'Green'
    uses: bakuppus/github-action-reuseable-workflow-multiple-inputs/.github/workflows/green-workflow-caller.yaml@dev
    with:
      username: ${{ inputs.username }}
    secrets:
      token: ${{ secrets.CICD_GIT_TOKEN }}
